### ISSUE TITLE
"The GPFS Hadoop connector open source process is still ongoing. Please stay tune..."

### ISSUE THREAD

**Issue by ehiggs** [ibmgpfs/GPFSHadoopConnector#1]
"The GPFS Hadoop connector open source process is still ongoing. Please stay tune..."

1 year on: any progress?

**Comment by ehiggs** [comment]
There is a citation on Wikipedia claiming that [IBM released this code.](https://en.wikipedia.org/wiki/Apache_Hadoop#cite_ref-27). It refers to [this ticket](https://issues.apache.org/jira/browse/HADOOP-6330), but there is no source attached there and it refers to [this](http://www-03.ibm.com/systems/clusters/software/gpfs/index.html) dead page. 

Any updates?

**Comment by ibmgpfs** [comment]
Hi,

The project had been handed over to other persons long ago and finally 
they decided to release the code somewhere else. My apology for that.

Is it the right action to cancel/delete the project out from gitHub or 
anything else I need to take action? Thanks!

Thanks & Best regards,

---

Lin Feng Shen 沈林峰

General Parallel File System
China Systems & Technology Lab, Beijing Tel: 86-10-82453535 Email: 
shenlinf@cn.ibm.com
Address: 28, ZhongGuanCun Software Park, No.8 Dong Bei Wang West Road, 
Haidian District Beijing P.R.China 100193

**Comment by ehiggs** [comment]
Hi Lin Feng.

> The project had been handed over to other persons long ago and finally they decided to release the code somewhere else.

Do you know where they released this?

> Is it the right action to cancel/delete the project out from gitHub or anything else I need to take action? Thanks!

Github is pretty popular, so if the code is released elsewhere, maybe it's a good idea to also put the code here so it has good visibility.

**Comment by ibmgpfs** [comment]
Ewan,

I checked with the owner. He wished to keep the page since we still had 
plan and customers had interest to post it on gitHub, but given the tight 
development schedule, he didn't commit the time line. Thanks for your 
understanding!

Thanks & Best regards,

---

Lin Feng Shen 沈林峰

General Parallel File System
China Systems & Technology Lab, Beijing Tel: 86-10-82453535 Email: 
shenlinf@cn.ibm.com
Address: 28, ZhongGuanCun Software Park, No.8 Dong Bei Wang West Road, 
Haidian District Beijing P.R.China 100193

**Comment by ehiggs** [comment]
Thanks.
